---
name: Publish Python package to PyPI

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  pypi:
    name: Build and upload to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Update pip
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install build and twine
        run: python -m pip install --upgrade build twine
      - name: Run build
        run: python -m build
      - name: Run twine check
        run: python -m twine check dist/*
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
